config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [] do 
    resources :photos 
  end

 	resources :photos, only: [] do 
    resources :comments
  end

  get '/photos', to: 'photos#show_all'
  root 'photos#show_all'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :photos, dependent: :destroy
	has_many :comments, dependent: :destroy 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@photo = Photo.find params[:photo_id]
		@comment = @photo.comments.new(comment_params)
		@comment.user = current_user
		@comment.save
		redirect_to user_photo_path(current_user, @photo)
	end
 
	def destroy
		@photo = Photo.find params[:photo_id]
		@comment = @photo.comments.find params[:id]
		@comment.destroy
		redirect_to user_photo_path(current_user, @photo)
	end

	def edit
		@photo = Photo.find params[:photo_id]
		@new_comment = @photo.comments.find params[:id]		
	end

	def update
		@photo = Photo.find params[:photo_id]
		@comment = @photo.comments.find params[:id]
		if @comment.update(comment_params)
			redirect_to user_photo_path(current_user, @photo)
		else
			render 'edit'
		end
	end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_action :authenticate_user!, except: [:show_all]
	def index
		@photos = current_user.photos
	end

	def show
		@photo = Photo.find params[:id]
		@new_comment = Comment.new(:photo => @photo)
	end

	def new
		@photo = current_user.photos.build
	end

	def edit
		@photo = current_user.photos.find(params[:id])
	end

	def create
		@photo= current_user.photos.build(photo_params)
		if @photo.save
			redirect_to user_photo_path(current_user, @photo)
		else
			render 'new'
		end
	end 

	def update
		@photo = Photo.find params[:id]
			if @photo.update(photo_params)
				redirect_to user_photo_path(current_user, @photo)
			else
				render 'edit'
			end
	end

	def destroy
		@photo = Photo.find params[:id]
		@photo.destroy

		redirect_to user_photos_path(current_user)
	end


	def show_all
		@photos = Photo.where(public: true)
	end

	private
		def photo_params
			params.require(:photo).permit(:public, :image, :caption)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/comments/_comment.html.erb
<p>
	<strong>Comment:</strong>
	<%= comment.body %>
</p>

<p>
	<%= link_to 'Edit Comment', edit_photo_comment_path(@photo, comment) %>
	<%= link_to 'Delete Comment', [comment.photo, comment],
	method: :delete,
	data: {confirm: 'Are you sure you want to delete this comment?'} 
	%>
</p>

app/views/comments/_form.html.erb
<%= simple_form_for([@photo, @new_comment]) do |f| %>
    <%= f.input :body %>
    <%= f.submit%>
<% end %>

app/views/comments/edit.html.erb
<h3>Edit your comment:</h3>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BruGram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1> Welcome to Brugram ! </h1>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= simple_form_for [current_user, @photo] do |f| %>
  <p>
    <%= f.input :public %><br>
  </p>
 
  <p>
    <%= f.input :image %><br>
  </p>
 
  <p>
    <%= f.input :caption %><br>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/photos/edit.html.erb
<h2>Edit BruGram</h2>

<%= render 'form' %>

<h4>
  <%= link_to 'Delete this Photo', user_photo_path(current_user, @photo),
  method: :delete,
  data: {confirm: 'Are you sure you want to delete this Photo?'} 
   %>
 </h4>

app/views/photos/index.html.erb
<div class = "container">

	<h1>My photos </h1>
	
	<div class= "row">
	<% @photos.each do |photo| %>
		<div class= "col-md-4">
			<p><%= photo.caption %></p>
			<p><%= link_to 'show', user_photo_path(current_user, photo) %></p>
			<%= image_tag photo.image %>
		</div>
<% end %>
</div>

<p><%= link_to 'New Photo', new_user_photo_path(current_user) %> | <%= link_to 'Back', photos_path %></p>

app/views/photos/new.html.erb
<h2>Make a new BruGram</h2>

<%= render 'form' %>
<p><%= link_to 'Back', photos_path %></p>

app/views/photos/show.html.erb
<p>
  <strong>Image:</strong>
  <%= image_tag @photo.image %>
</p>
 
<p>
  <strong>Caption:</strong>
  <%= @photo.caption%>
</p>
 
<%= render @photo.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'View your photos', user_photos_path(current_user) %> |
<%= link_to 'Edit', edit_user_photo_path(current_user, @photo) %> |
<%= link_to 'Back', photos_path %> 

app/views/photos/show_all.html.erb
<div class = "container">
 	
 	<h1>Public photos</h1>

 	<div class= "row">

		<% @photos.each do |photo| %>
		<div class= "col-md-4">
		<p><%= photo.caption %> | <%= link_to 'show', user_photo_path(photo.user, photo) %></p>
		<p> <%= image_tag photo.image %> </p>
		</div>
	<% end %>
	</div>

<% if current_user %>
	<p><%= link_to 'View your photos', user_photos_path(current_user) %> | <%= link_to 'New photo', new_user_photo_path(current_user) %></p>
<% end %>